site_name: srclib
site_description: srclib is a hackable, polyglot code analysis library.

docs_dir: sources

repo_url: https://sourcegraph.com/sourcegraph/srclib/

dev_addr: '0.0.0.0:8000'

theme_dir: ./theme/

google_analytics: ['UA-40540747-5', 'srclib.org']

pages:

- ['gettingstarted.md', 'Getting Started']

# Editor Plugins
- ['plugins/emacs.md', 'Editor Plugins', 'Emacs']
- ['plugins/sublimetext.md', 'Editor Plugins', 'Sublime Text']
#- ['plugins/vim.md', 'Editor Plugins', 'Vim']
- ['plugins/atom.md', 'Editor Plugins', 'Atom']
#- ['plugins/creatingaplugin.md', 'Editor Plugins', 'Creating a Plugin']

# Language Toolchains
- ['toolchains/python.md', 'Language Toolchains', 'Python']
- ['toolchains/go.md', 'Language Toolchains', 'Go']
- ['toolchains/ruby.md', 'Language Toolchains', 'Ruby']
- ['toolchains/javascript.md', 'Language Toolchains', 'JavaScript']
#- ['toolchains/java.md', 'Language Toolchains', 'Java']

# Building
#- ['building/uploading.md', 'Library Authors', 'Uploading to Sourcegraph']

# API
- ['api/overview.md', 'Building on srclib', 'Overview']
- ['api/make.md', 'Building on srclib', 'src make']
- ['api/describe.md', 'Building on srclib', 'src describe']

# Creating a Toolchain
- ['toolchains/overview.md', 'Contributing to srclib', 'Creating a Toolchain']
- ['toolchains/openquestions.md', 'Contributing to srclib', 'Open Questions']

#- ['toolchains/formatter.md', 'Creating a Toolchain', 'Formatter API']


# Data Model
- ['api/data-model.md', 'Data Model', 'Overview']
- ['toolchains/commonstructures.md', 'Data Model', 'Common Data Structures']
- ['toolchains/scanner-output.md', 'Data Model', 'Scanner Output']
- ['toolchains/grapher-output.md', 'Data Model', 'Grapher Output']
- ['toolchains/dependency-resolution-output.md', 'Data Model', 'Dependency Resolution Output']

- ['faq.md', 'FAQ']
